### PR TITLE
updates to "what is this?"

### LINKED ISSUE #7: Add "People" page
Include description of each person with role in organization

### PR DESCRIPTION
**Pull request by k8hertweck**
- changed title to "About"
- added separate sections for "Mission" and "People"
- included current participants with links and brief description

resolves #7

### CODE REVIEW

**Comment by k8hertweck** [comment]
Checking with @matsen @bcclaywell @barngab10 to make sure this looks ok!

**Review by matsen — APPROVED** [review]

**Comment by ghost** [comment]
@k8hertweck Looks good to me! It might be better if I am listed as Gabrielle. I don't show up on Centernet search under Gabi :)

**Comment by k8hertweck** [comment]
Great, updated your name, thanks!

**Comment by bcclaywell** [comment]
Looks good to me!

**Pull request merged**
